# Generated by Django 5.1.1 on 2024-09-28 13:24

from django.db import migrations

from core.migrations.custom_migrations.create_schemas import CREATE_SCHEMAS


class Migration(migrations.Migration):

    dependencies = []

    operations = [migrations.RunSQL(sql=CREATE_SCHEMAS)]
