# Generated by Django 5.1.1 on 2024-09-28 13:14

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": '"vyapar"."shop_categories"',
            },
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "location",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.DecimalField(decimal_places=6, max_digits=9), size=2
                    ),
                ),
                ("gst_number", models.CharField(blank=True, max_length=15, null=True)),
                ("invoice", models.TextField(blank=True, null=True)),
                ("shop_image", models.TextField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="%(class)s_owner", to="user.user"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shop_categories",
                        to="shop.shopcategory",
                    ),
                ),
            ],
            options={
                "db_table": '"vyapar"."shops"',
            },
        ),
    ]
