# Generated by Django 5.1.1 on 2024-09-28 08:58

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("contact_number", models.CharField(max_length=255, unique=True)),
                ("aadhar_number", models.CharField(max_length=255, unique=True)),
                ("pan_number", models.CharField(max_length=255, unique=True)),
                ("is_setup_completed", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "users",
            },
        ),
    ]
